# Generated by Django 3.1.4 on 2020-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('NewRecovered', models.BigIntegerField()),
                ('TotalRecovered', models.BigIntegerField()),
                ('Country', models.CharField(max_length=30)),
                ('CountryCode', models.CharField(max_length=30)),
                ('Slug', models.CharField(max_length=30)),
                ('NewConfirmed', models.BigIntegerField()),
                ('TotalConfirmed', models.BigIntegerField()),
                ('NewDeaths', models.BigIntegerField()),
                ('TotalDeaths', models.BigIntegerField()),
            ],
        ),
    ]
