# Generated by Django 3.1.4 on 2020-12-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid19',
            name='Index',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
